kafka-topics:
  raw-events-stream: &RAW_EVENTS_STREAM incoming-event-stream-test

internal-resources:
  files:
    - name: data
      path: ${DATA_FILE_PATH:C:/Hacks/TechLeaders2022/trek3-city_service_tasks_monitoring/projects/small_data_100.csv}

reactor-kafka-config:
  bootstrap-servers: ${KAFKA_BROKERS:188.72.108.143:9094,45.9.24.88:9094,87.242.121.153:9094}
  bindings:
    alldata-out-0:
      destination: *RAW_EVENTS_STREAM
  connections:
    alldata-out-0:
      producer:
        client-id: "raw-events-sender"
        acks: "all"
        key-serializer: "integer"
        value-serializer: "string"

external-resources:
  someapi:
    base-url: ${EXT_API_BASE_URL:https://google.com}

springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api/get-full-specs
    enabled: true

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false    # in this example project we build an empty DTO with no fields
