internal-resources:
  files:
    - name: data
      path: ${DATA_FILE_PATH:C:/Hacks/TechLeaders2022/trek3-city_service_tasks_monitoring/projects/small_data_100.csv}

external-resources:
  someapi:
    base-url: ${EXT_API_BASE_URL:https://google.com}

springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api/get-full-specs
    enabled: true

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false    # in this example project we build an empty DTO with no fields
